<?php
//Do not allow directly accessing this file
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


if ( ! lct_get_setting( 'acf_dev' ) ):

	acf_add_local_field_group( [
		'key'                        => 'group_55b94b2bcdb25',
		'title'                      => 'General',
		'fields'                     => [
			[
				'key'               => 'field_5977d71682015',
				'label'             => 'General',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
				'menu_order'        => 0,
			],
			[
				'key'                       => 'field_55ce9ee4e2e26',
				'label'                     => 'LCT\'s Avada.css',
				'name'                      => 'lct:::disable_avada_css',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 0,
				'ui'                        => 1,
				'ui_on_text'                => 'Disable',
				'ui_off_text'               => 'Enable',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 1,
			],
			[
				'key'                       => 'field_5716edeac6790',
				'label'                     => 'LCT\'s Avada-page_defaults.css',
				'name'                      => 'lct:::enable_avada_css_page_defaults',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 0,
				'ui'                        => 1,
				'ui_on_text'                => 'Disable',
				'ui_off_text'               => 'Enable',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 2,
			],
			[
				'key'                       => 'field_58700d9dc01ca',
				'label'                     => 'Underline Links',
				'name'                      => 'lct:::underline_links',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 1,
				'ui'                        => 1,
				'ui_on_text'                => '',
				'ui_off_text'               => '',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 3,
			],
			[
				'key'                       => 'field_5977a6631b6c2',
				'label'                     => 'Use Border Bottom',
				'name'                      => 'lct:::border_underline_links',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 0,
				'ui'                        => 1,
				'ui_on_text'                => 'Border Bottom',
				'ui_off_text'               => 'Decoration',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 4,
			],
			[
				'key'                       => 'field_5977a6e01b6c4',
				'label'                     => 'Border Thickness',
				'name'                      => 'lct:::border_underline_links_thickness',
				'aria-label'                => '',
				'type'                      => 'number',
				'instructions'              => '',
				'required'                  => 1,
				'conditional_logic'         => [
					[
						[
							'field'    => 'field_5977a6631b6c2',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'                   => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'             => 1,
				'placeholder'               => '',
				'prepend'                   => '',
				'append'                    => '',
				'min'                       => 1,
				'max'                       => 99,
				'step'                      => '',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 5,
			],
			[
				'key'               => 'field_5977a7261b6c5',
				'label'             => 'Border Color',
				'name'              => 'lct:::border_underline_links_color',
				'aria-label'        => '',
				'type'              => 'color_picker',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_5977a6631b6c2',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '#CCCCCC',
				'enable_opacity'    => false,
				'return_format'     => 'string',
				'menu_order'        => 6,
			],
			[
				'key'               => 'field_5977a78674ff5',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 7,
			],
			[
				'key'                       => 'field_587011506385e',
				'label'                     => 'Underline Links in Header',
				'name'                      => 'lct:::underline_links_header',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 0,
				'ui'                        => 1,
				'ui_on_text'                => '',
				'ui_off_text'               => '',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 8,
			],
			[
				'key'                       => 'field_5716f281ee4e8',
				'label'                     => 'Set Page Title Bar height to auto',
				'name'                      => 'lct:::page_title_bar_auto',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '30',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 1,
				'ui'                        => 1,
				'ui_on_text'                => '',
				'ui_off_text'               => '',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 9,
			],
			[
				'key'                       => 'field_5716f2dbee4e9',
				'label'                     => 'Page Title Bar Top Padding',
				'name'                      => 'lct:::page_title_bar_padding_top',
				'aria-label'                => '',
				'type'                      => 'text',
				'instructions'              => '',
				'required'                  => 1,
				'conditional_logic'         => [
					[
						[
							'field'    => 'field_5716f281ee4e8',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'                   => [
					'width' => '35',
					'class' => '',
					'id'    => '',
				],
				'default_value'             => 10,
				'placeholder'               => '',
				'prepend'                   => '',
				'append'                    => '',
				'maxlength'                 => 4,
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 10,
			],
			[
				'key'                       => 'field_5716f307ee4ea',
				'label'                     => 'Page Title Bar Bottom Padding',
				'name'                      => 'lct:::page_title_bar_padding_bottom',
				'aria-label'                => '',
				'type'                      => 'text',
				'instructions'              => '',
				'required'                  => 1,
				'conditional_logic'         => [
					[
						[
							'field'    => 'field_5716f281ee4e8',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'                   => [
					'width' => '35',
					'class' => '',
					'id'    => '',
				],
				'default_value'             => 10,
				'placeholder'               => '',
				'prepend'                   => '',
				'append'                    => '',
				'maxlength'                 => 4,
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 11,
			],
			[
				'key'               => 'field_5977a855c94fb',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 12,
			],
			[
				'key'                       => 'field_56e1f527a2803',
				'label'                     => 'Excerpt Read More Replacement',
				'name'                      => 'lct:::avada::is_post_excerpt_read_more',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '30',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 0,
				'ui'                        => 1,
				'ui_on_text'                => '',
				'ui_off_text'               => '',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 13,
			],
			[
				'key'                       => 'field_58b0bae411a92',
				'label'                     => 'Only allow on certain pages',
				'name'                      => 'lct:::avada::is_post_excerpt_read_more_certain_pages',
				'aria-label'                => '',
				'type'                      => 'true_false',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => [
					[
						[
							'field'    => 'field_56e1f527a2803',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'                   => [
					'width' => '35',
					'class' => '',
					'id'    => '',
				],
				'message'                   => '',
				'default_value'             => 0,
				'ui'                        => 1,
				'ui_on_text'                => '',
				'ui_off_text'               => '',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 14,
			],
			[
				'key'                       => 'field_58b0baea11a93',
				'label'                     => 'Allowed Pages',
				'name'                      => 'lct:::avada::post_excerpt_read_more_certain_pages',
				'aria-label'                => '',
				'type'                      => 'post_object',
				'instructions'              => '',
				'required'                  => 1,
				'conditional_logic'         => [
					[
						[
							'field'    => 'field_56e1f527a2803',
							'operator' => '==',
							'value'    => '1',
						],
						[
							'field'    => 'field_58b0bae411a92',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'                   => [
					'width' => '35',
					'class' => '',
					'id'    => '',
				],
				'post_type'                 => [
					0 => 'page',
				],
				'taxonomy'                  => [
				],
				'allow_null'                => 1,
				'multiple'                  => 1,
				'return_format'             => 'object',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'ui'                        => 1,
				'bidirectional_target'      => [
				],
				'menu_order'                => 15,
			],
			[
				'key'                       => 'field_55b94b4f5caa0',
				'label'                     => 'Post Excerpt Read More Replacement',
				'name'                      => 'lct:::avada::post_excerpt_read_more',
				'aria-label'                => '',
				'type'                      => 'textarea',
				'instructions'              => 'Replace [...] with what ever you want.',
				'required'                  => 0,
				'conditional_logic'         => [
					[
						[
							'field'    => 'field_56e1f527a2803',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'                   => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'             => '',
				'placeholder'               => '',
				'maxlength'                 => '',
				'rows'                      => 3,
				'new_lines'                 => 'br',
				'lct_class_selector'        => '',
				'lct_roles_n_caps'          => '',
				'lct_roles_n_caps_viewonly' => '',
				'menu_order'                => 16,
			],
			[
				'key'               => 'field_5977a860c94fd',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 17,
			],
			[
				'key'               => 'field_5977d71b82016',
				'label'             => 'Advanced',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
				'menu_order'        => 18,
			],
			[
				'key'                => 'field_58752185e06d1',
				'label'              => 'Disable Avada\'s social link icons that are printed in the footer',
				'name'               => 'lct:::disable_social_footer',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Disable',
				'ui_off_text'        => 'Enable',
				'lct_class_selector' => '',
				'menu_order'         => 19,
			],
			[
				'key'                => 'field_5866ae4ae2d94',
				'label'              => 'Enable Avada\'s Blog Sidebar',
				'name'               => 'lct:::enable_avada-blog-sidebar',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Enable',
				'ui_off_text'        => 'Disable',
				'lct_class_selector' => '',
				'menu_order'         => 20,
			],
			[
				'key'                => 'field_56e9da87e4d78',
				'label'              => 'Disable Image Sizes',
				'name'               => 'lct:::disable_image_sizes',
				'aria-label'         => '',
				'type'               => 'select',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'            => [
					'blog-large'             => 'blog-large',
					'blog-medium'            => 'blog-medium',
					'portfolio-full'         => 'portfolio-full',
					'portfolio-one'          => 'portfolio-one',
					'portfolio-two'          => 'portfolio-two',
					'portfolio-three'        => 'portfolio-three',
					'portfolio-four'         => 'portfolio-four',
					'portfolio-five'         => 'portfolio-five',
					'recent-posts'           => 'recent-posts',
					'recent-works-thumbnail' => 'recent-works-thumbnail',
					'fusion-200'             => 'fusion-200',
					'fusion-400'             => 'fusion-400',
					'fusion-600'             => 'fusion-600',
					'fusion-800'             => 'fusion-800',
					'fusion-1200'            => 'fusion-1200',
					'tabs-img'               => 'OLD: tabs-img',
					'related-img'            => 'OLD: related-img',
					'portfolio-six'          => 'OLD: portfolio-six',
				],
				'default_value'      => [
					0  => 'blog-large',
					1  => 'portfolio-full',
					2  => 'portfolio-one',
					3  => 'portfolio-two',
					4  => 'portfolio-three',
					5  => 'portfolio-four',
					6  => 'portfolio-five',
					7  => 'recent-posts',
					8  => 'recent-works-thumbnail',
					9  => 'fusion-200',
					10 => 'fusion-400',
					11 => 'fusion-600',
					12 => 'fusion-800',
					13 => 'fusion-1200',
					14 => 'tabs-img',
					15 => 'related-img',
					16 => 'portfolio-six',
				],
				'allow_null'         => 1,
				'multiple'           => 1,
				'ui'                 => 1,
				'ajax'               => 0,
				'return_format'      => 'value',
				'lct_preset_choices' => '',
				'lct_class_selector' => '',
				'placeholder'        => '',
				'menu_order'         => 21,
			],
			[
				'key'                => 'field_5833547d6b180',
				'label'              => 'Remove Avada Options Meta Box for post_types',
				'name'               => 'lct:::remove_avada_options_post_types',
				'aria-label'         => '',
				'type'               => 'select',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'            => [
				],
				'default_value'      => [
					0 => 'lct_theme_chunk',
				],
				'allow_null'         => 1,
				'multiple'           => 1,
				'ui'                 => 1,
				'ajax'               => 1,
				'return_format'      => 'value',
				'lct_preset_choices' => 'pretty_wp_post_types',
				'lct_class_selector' => '',
				'placeholder'        => '',
				'menu_order'         => 22,
			],
			[
				'key'                => 'field_56d745ecb3f8d',
				'label'              => 'Show Sandbox Warning',
				'name'               => 'lct:::show_sandbox_warning',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => '',
				'ui_off_text'        => '',
				'lct_class_selector' => '',
				'menu_order'         => 23,
			],
			[
				'key'                => 'field_56d74658b3f8e',
				'label'              => 'For Dev',
				'name'               => 'lct:::show_sandbox_warning_dev',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => [
					[
						[
							'field'    => 'field_56d745ecb3f8d',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'            => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => '',
				'ui_off_text'        => '',
				'lct_class_selector' => '',
				'menu_order'         => 24,
			],
			[
				'key'                => 'field_56d74678b3f8f',
				'label'              => 'For Sandbox',
				'name'               => 'lct:::show_sandbox_warning_sandbox',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => [
					[
						[
							'field'    => 'field_56d745ecb3f8d',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'            => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => '',
				'ui_off_text'        => '',
				'lct_class_selector' => '',
				'menu_order'         => 25,
			],
			[
				'key'                => 'field_56d74c81337e3',
				'label'              => 'Sandbox Warning on the Side',
				'name'               => 'lct:::show_sandbox_warning_side',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => [
					[
						[
							'field'    => 'field_56d745ecb3f8d',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'            => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Show',
				'ui_off_text'        => 'Hide',
				'lct_class_selector' => '',
				'menu_order'         => 26,
			],
			[
				'key'                => 'field_5d0bf0b88065e',
				'label'              => 'Theme Support: Enable Fusion Builder Demos',
				'name'               => 'lct:::enable_fb_demos',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'            => '',
				'default_value'      => 0,
				'ui'                 => 1,
				'ui_on_text'         => 'Enable',
				'ui_off_text'        => 'Disable',
				'lct_class_selector' => '',
				'menu_order'         => 27,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_Avada',
				],
			],
		],
		'menu_order'                 => 5,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_586ade8dd99dd',
		'title'                      => 'Header',
		'fields'                     => [
			[
				'key'                => 'field_586ade9fea52a',
				'label'              => 'Mobile Menu Button Text in Header',
				'name'               => 'lct:::menu_button_text_in_header',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 1,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Show',
				'ui_off_text'        => 'Hide',
				'lct_class_selector' => '',
				'menu_order'         => 0,
			],
			[
				'key'                => 'field_586adf25ea52b',
				'label'              => 'Mobile Menu Button Text in Header When Header is Sticky',
				'name'               => 'lct:::menu_button_text_in_header_sticky',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Show',
				'ui_off_text'        => 'Hide',
				'lct_class_selector' => '',
				'menu_order'         => 1,
			],
			[
				'key'               => 'field_586b137edcfa5',
				'label'             => 'Mobile Nav Bar Text Color',
				'name'              => 'lct:::mobi_nav_bar_color',
				'aria-label'        => '',
				'type'              => 'color_picker',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'enable_opacity'    => false,
				'return_format'     => 'string',
				'menu_order'        => 2,
			],
			[
				'key'               => 'field_586b1417dcfa8',
				'label'             => 'Mobile Nav Bar Text Color Hover',
				'name'              => 'lct:::mobi_nav_bar_color_hover',
				'aria-label'        => '',
				'type'              => 'color_picker',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'enable_opacity'    => false,
				'return_format'     => 'string',
				'menu_order'        => 3,
			],
			[
				'key'               => 'field_586b13d8dcfa6',
				'label'             => 'Mobile Nav Bar Background Color',
				'name'              => 'lct:::mobi_nav_bar_bg_color',
				'aria-label'        => '',
				'type'              => 'color_picker',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'enable_opacity'    => false,
				'return_format'     => 'string',
				'menu_order'        => 4,
			],
			[
				'key'               => 'field_586b13ecdcfa7',
				'label'             => 'Mobile	Nav Bar Background Color Hover',
				'name'              => 'lct:::mobi_nav_bar_bg_color_hover',
				'aria-label'        => '',
				'type'              => 'color_picker',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '25',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'enable_opacity'    => false,
				'return_format'     => 'string',
				'menu_order'        => 5,
			],
			[
				'key'                => 'field_586adfa01ae6f',
				'label'              => 'Header Layouts',
				'name'               => '',
				'aria-label'         => '',
				'type'               => 'message',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'            => '<h3>Here are the default Views that we are concerned about:</h3>

<h4>Desktop :: (Greater than 1024px)</h4>
<ul>
	<li>Desktop - Home</li>
	<li>Desktop - Home Sticky</li>
	<li>Desktop - Default</li>
	<li>Desktop - Sticky</li>
</ul>

<h4>Tablet :: (between 768px & 1024px)</h4>
<ul>
	<li>Tablet - Home</li>
	<li>Tablet - Home Sticky</li>
	<li>Tablet - Default</li>
	<li>Tablet - Sticky</li>
</ul>

<h4>Mobile :: (Less than 768px)</h4>
<ul>
	<li>Mobile - Home</li>
	<li>Mobile - Home Sticky</li>
	<li>Mobile - Default</li>
	<li>Mobile - Sticky</li>
</ul>',
				'esc_html'           => 0,
				'new_lines'          => '',
				'lct_class_selector' => '',
				'menu_order'         => 6,
			],
			[
				'key'                => 'field_586ae0d0a88e6',
				'label'              => 'Header Layout: Homepage',
				'name'               => 'lct:::is_header_layout_home',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Use a Custom Theme Chunk',
				'ui_off_text'        => 'Use Avada Default Layout',
				'lct_class_selector' => '',
				'menu_order'         => 7,
			],
			[
				'key'                  => 'field_586ae2f599385',
				'label'                => 'Custom Layout',
				'name'                 => 'lct:::header_layout_home',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => [
					[
						[
							'field'    => 'field_586ae0d0a88e6',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'              => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'post_type'            => [
					0 => 'lct_theme_chunk',
				],
				'taxonomy'             => [
				],
				'allow_null'           => 1,
				'multiple'             => 0,
				'return_format'        => 'id',
				'ui'                   => 1,
				'lct_class_selector'   => '',
				'bidirectional_target' => [
				],
				'menu_order'           => 8,
			],
			[
				'key'               => 'field_586ae4c2ada39',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 9,
			],
			[
				'key'                => 'field_586ae157a88e7',
				'label'              => 'Header Layout: All Other Pages',
				'name'               => 'lct:::is_header_layout',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Use a Custom Theme Chunk',
				'ui_off_text'        => 'Use Avada Default Layout',
				'lct_class_selector' => '',
				'menu_order'         => 10,
			],
			[
				'key'                  => 'field_586ae36722a24',
				'label'                => 'Custom Layout',
				'name'                 => 'lct:::header_layout',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => [
					[
						[
							'field'    => 'field_586ae157a88e7',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'              => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'post_type'            => [
					0 => 'lct_theme_chunk',
				],
				'taxonomy'             => [
				],
				'allow_null'           => 1,
				'multiple'             => 0,
				'return_format'        => 'id',
				'ui'                   => 1,
				'lct_class_selector'   => '',
				'bidirectional_target' => [
				],
				'menu_order'           => 11,
			],
			[
				'key'               => 'field_586b3615471a2',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 12,
			],
			[
				'key'                => 'field_586b362f471a7',
				'label'              => 'After Header Layout: Homepage',
				'name'               => 'lct:::is_after_header_layout_home',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Use a Custom Theme Chunk',
				'ui_off_text'        => 'Use Avada Default Layout',
				'lct_class_selector' => '',
				'menu_order'         => 13,
			],
			[
				'key'                  => 'field_586b362f471a6',
				'label'                => 'After Custom Layout',
				'name'                 => 'lct:::after_header_layout_home',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => [
					[
						[
							'field'    => 'field_586b362f471a7',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'              => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'post_type'            => [
					0 => 'lct_theme_chunk',
				],
				'taxonomy'             => [
				],
				'allow_null'           => 1,
				'multiple'             => 0,
				'return_format'        => 'id',
				'ui'                   => 1,
				'lct_class_selector'   => '',
				'bidirectional_target' => [
				],
				'menu_order'           => 14,
			],
			[
				'key'               => 'field_586b361d471a3',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 15,
			],
			[
				'key'                => 'field_586b361f471a5',
				'label'              => 'After Header Layout: All Other Pages',
				'name'               => 'lct:::is_after_header_layout',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Use a Custom Theme Chunk',
				'ui_off_text'        => 'Use Avada Default Layout',
				'lct_class_selector' => '',
				'menu_order'         => 16,
			],
			[
				'key'                  => 'field_586b361e471a4',
				'label'                => 'Custom Layout',
				'name'                 => 'lct:::after_header_layout',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => [
					[
						[
							'field'    => 'field_586b361f471a5',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'              => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'post_type'            => [
					0 => 'lct_theme_chunk',
				],
				'taxonomy'             => [
				],
				'allow_null'           => 1,
				'multiple'             => 0,
				'return_format'        => 'id',
				'ui'                   => 1,
				'lct_class_selector'   => '',
				'bidirectional_target' => [
				],
				'menu_order'           => 17,
			],
			[
				'key'               => 'field_5a3ac616fba22',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 18,
			],
			[
				'key'                => 'field_5a3ad035b31d0',
				'label'              => 'Bottom Mobile Menu Layout: Home',
				'name'               => 'lct:::is_bottom_mobile_menu_layout_home',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'message'            => '',
				'default_value'      => 0,
				'ui'                 => 1,
				'ui_on_text'         => 'Use a Custom Theme Chunk',
				'ui_off_text'        => 'Use Avada Default Layout',
				'lct_class_selector' => '',
				'menu_order'         => 19,
			],
			[
				'key'                  => 'field_5a3ad034b31cf',
				'label'                => 'Custom Layout',
				'name'                 => 'lct:::bottom_mobile_menu_layout_home',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => [
					[
						[
							'field'    => 'field_5a3ad035b31d0',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'              => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'post_type'            => [
					0 => 'lct_theme_chunk',
				],
				'taxonomy'             => [
				],
				'allow_null'           => 1,
				'multiple'             => 0,
				'return_format'        => 'id',
				'lct_class_selector'   => '',
				'ui'                   => 1,
				'bidirectional_target' => [
				],
				'menu_order'           => 20,
			],
			[
				'key'               => 'field_5a3ad036b31d1',
				'label'             => 'DomPDF Clear',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dompdf_clear',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 21,
			],
			[
				'key'                => 'field_5a3ac615fba21',
				'label'              => 'Bottom Mobile Menu Layout: All Other Pages',
				'name'               => 'lct:::is_bottom_mobile_menu_layout',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'message'            => '',
				'default_value'      => 0,
				'ui'                 => 1,
				'ui_on_text'         => 'Use a Custom Theme Chunk',
				'ui_off_text'        => 'Use Avada Default Layout',
				'lct_class_selector' => '',
				'menu_order'         => 22,
			],
			[
				'key'                  => 'field_5a3ac615fba20',
				'label'                => 'Custom Layout',
				'name'                 => 'lct:::bottom_mobile_menu_layout',
				'aria-label'           => '',
				'type'                 => 'post_object',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => [
					[
						[
							'field'    => 'field_5a3ac615fba21',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'              => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'post_type'            => [
					0 => 'lct_theme_chunk',
				],
				'taxonomy'             => [
				],
				'allow_null'           => 1,
				'multiple'             => 0,
				'return_format'        => 'id',
				'lct_class_selector'   => '',
				'ui'                   => 1,
				'bidirectional_target' => [
				],
				'menu_order'           => 23,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_Avada',
				],
			],
		],
		'menu_order'                 => 6,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

endif;
