<?php
//Do not allow directly accessing this file
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


if ( ! lct_get_setting( 'acf_dev' ) ):

	acf_add_local_field_group( [
		'key'                        => 'group_58434b9797e57',
		'title'                      => 'Dev Report',
		'fields'                     => [
			[
				'key'               => 'field_58434bad2da02',
				'label'             => 'Plugins & editzz File Statuses',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dev_report',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 0,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_dev',
				],
			],
		],
		'menu_order'                 => 13,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_59a5bfe70b3bf',
		'title'                      => 'Modified Posts',
		'fields'                     => [
			[
				'key'                => 'field_59a5c59a2d518',
				'label'              => 'Check for posts modified on and after this date',
				'name'               => 'lct:::modified_posts_last_check',
				'aria-label'         => '',
				'type'               => 'date_time_picker',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'display_format'     => 'F j, Y g:iA',
				'return_format'      => 'Y-m-d H:i:s',
				'first_day'          => 0,
				'lct_class_selector' => '',
				'menu_order'         => 0,
			],
			[
				'key'               => 'field_59a5bfe71bb40',
				'label'             => 'Modified Posts',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dev_report',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 1,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_dev',
				],
			],
		],
		'menu_order'                 => 14,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_5d2e4f29240bb',
		'title'                      => 'Database Status: postmeta Table',
		'fields'                     => [
			[
				'key'               => 'field_5d2e4f2945b8a',
				'label'             => 'Database Status: postmeta Table',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dev_report',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 0,
			],
			[
				'key'                => 'field_5d2e4f2946343',
				'label'              => 'Ignore Keys',
				'name'               => 'lct:::db_status::postmeta::ignore_keys',
				'aria-label'         => '',
				'type'               => 'select',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'            => [
				],
				'default_value'      => [
					0  => '_action_manager_schedule',
					1  => '_menu_item_classes',
					2  => '_menu_item_fusion_megamenu',
					3  => '_menu_item_menu_item_parent',
					4  => '_menu_item_object',
					5  => '_menu_item_object_id',
					6  => '_menu_item_target',
					7  => '_menu_item_type',
					8  => '_menu_item_url',
					9  => '_menu_item_xfn',
					10 => '_wp_attached_file',
					11 => '_wp_attachment_metadata',
					12 => '_wp_page_template',
					13 => '_yoast_wpseo_content_score',
					14 => '_yoast_wpseo_meta-robots-noindex',
					15 => '_yoast_wpseo_primary_category',
					16 => 'alert_meta',
					17 => 'alert_type',
					18 => 'avada_post_views_count',
					19 => 'dismissable',
					20 => 'expiration',
					21 => 'fusion_builder_converted',
					22 => 'fusion_builder_status',
					23 => 'kd_featured-image-2_page_id',
					24 => 'kd_featured-image-3_page_id',
					25 => 'kd_featured-image-4_page_id',
					26 => 'kd_featured-image-5_page_id',
					27 => 'location',
					28 => 'map',
					29 => 'notification_id',
					30 => 'plans',
					31 => 'slide_template',
					32 => 'type',
					33 => 'version',
					34 => 'viewed',
				],
				'allow_null'         => 1,
				'multiple'           => 1,
				'ui'                 => 1,
				'ajax'               => 0,
				'return_format'      => 'value',
				'lct_preset_choices' => '',
				'lct_class_selector' => '',
				'placeholder'        => '',
				'menu_order'         => 1,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_dev',
				],
			],
		],
		'menu_order'                 => 25,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_5d2e4f38a20da',
		'title'                      => 'Database Status: usermeta Table',
		'fields'                     => [
			[
				'key'               => 'field_5d2e4f38c0c4d',
				'label'             => 'Database Status: usermeta Table',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dev_report',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 0,
			],
			[
				'key'                => 'field_5d2e4f38c1426',
				'label'              => 'Ignore Keys',
				'name'               => 'lct:::db_status::usermeta::ignore_keys',
				'aria-label'         => '',
				'type'               => 'select',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'            => [
				],
				'default_value'      => [
				],
				'allow_null'         => 1,
				'multiple'           => 1,
				'ui'                 => 1,
				'ajax'               => 0,
				'return_format'      => 'value',
				'lct_preset_choices' => '',
				'lct_class_selector' => '',
				'placeholder'        => '',
				'menu_order'         => 1,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_dev',
				],
			],
		],
		'menu_order'                 => 26,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_5d2df40b58fa7',
		'title'                      => 'Database Status: options Table',
		'fields'                     => [
			[
				'key'               => 'field_5d2df427e8996',
				'label'             => 'Database Status: options Table',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'lct_dev_report',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'menu_order'        => 0,
			],
			[
				'key'                => 'field_5d2e351bd2a11',
				'label'              => 'Large Option Value Limit',
				'name'               => 'lct:::db_status::options::large_option_value_limit',
				'aria-label'         => '',
				'type'               => 'number',
				'instructions'       => '',
				'required'           => 1,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 1000,
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'min'                => 1,
				'max'                => '',
				'step'               => 1,
				'lct_class_selector' => '',
				'menu_order'         => 1,
			],
			[
				'key'                => 'field_5d2e141b15a27',
				'label'              => 'Ignore Option Names',
				'name'               => 'lct:::db_status::options::ignore_names',
				'aria-label'         => '',
				'type'               => 'select',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'            => [
				],
				'default_value'      => [
					0   => 'acf_pro_license',
					1   => 'acf_version',
					2   => 'active_plugins',
					3   => 'admin_email',
					4   => 'auto_core_update_notified',
					5   => 'avada_38_migrate',
					6   => 'avada_disable_builder',
					7   => 'avada_disable_encoding',
					8   => 'avada_migrations',
					9   => 'avada_permalinks',
					10  => 'avada_previous_version',
					11  => 'avada_revslider_version',
					12  => 'avada_version',
					13  => 'avatar_default',
					14  => 'avatar_rating',
					15  => 'bj_lazy_load_options',
					16  => 'blacklist_keys',
					17  => 'blog_charset',
					18  => 'blog_public',
					19  => 'blogdescription',
					20  => 'blogname',
					21  => 'can_compress_scripts',
					22  => 'category_base',
					23  => 'category_children',
					24  => 'close_comments_days_old',
					25  => 'close_comments_for_old_posts',
					26  => 'comment_max_links',
					27  => 'comment_moderation',
					28  => 'comment_order',
					29  => 'comment_registration',
					30  => 'comment_whitelist',
					31  => 'comments_notify',
					32  => 'comments_per_page',
					33  => 'cron',
					34  => 'current_theme',
					35  => 'current_theme_supports_woocommerce',
					36  => 'custom_image_sizes',
					37  => 'dashboard_widget_options',
					38  => 'date_format',
					39  => 'db_upgraded',
					40  => 'db_version',
					41  => 'default_category',
					42  => 'default_comment_status',
					43  => 'default_comments_page',
					44  => 'default_email_category',
					45  => 'default_link_category',
					46  => 'default_ping_status',
					47  => 'default_pingback_flag',
					48  => 'default_post_format',
					49  => 'default_product_cat',
					50  => 'default_role',
					51  => 'dnh_dismissed_notices',
					52  => 'duplicate_post_blacklist',
					53  => 'duplicate_post_copyattachments',
					54  => 'duplicate_post_copyauthor',
					55  => 'duplicate_post_copychildren',
					56  => 'duplicate_post_copycomments',
					57  => 'duplicate_post_copycontent',
					58  => 'duplicate_post_copydate',
					59  => 'duplicate_post_copyexcerpt',
					60  => 'duplicate_post_copyformat',
					61  => 'duplicate_post_copymenuorder',
					62  => 'duplicate_post_copypassword',
					63  => 'duplicate_post_copyslug',
					64  => 'duplicate_post_copystatus',
					65  => 'duplicate_post_copytemplate',
					66  => 'duplicate_post_copythumbnail',
					67  => 'duplicate_post_copytitle',
					68  => 'duplicate_post_increase_menu_order_by',
					69  => 'duplicate_post_roles',
					70  => 'duplicate_post_show_adminbar',
					71  => 'duplicate_post_show_bulkactions',
					72  => 'duplicate_post_show_notice',
					73  => 'duplicate_post_show_row',
					74  => 'duplicate_post_show_submitbox',
					75  => 'duplicate_post_taxonomies_blacklist',
					76  => 'duplicate_post_title_prefix',
					77  => 'duplicate_post_title_suffix',
					78  => 'duplicate_post_types_enabled',
					79  => 'duplicate_post_version',
					80  => 'ewww_image_optimizer_allow_tracking',
					81  => 'ewww_image_optimizer_auto',
					82  => 'ewww_image_optimizer_aux_folders_completed',
					83  => 'ewww_image_optimizer_aux_last',
					84  => 'ewww_image_optimizer_aux_paths',
					85  => 'ewww_image_optimizer_aux_resume',
					86  => 'ewww_image_optimizer_aux_type',
					87  => 'ewww_image_optimizer_background_optimization',
					88  => 'ewww_image_optimizer_backup_files',
					89  => 'ewww_image_optimizer_bulk_resume',
					90  => 'ewww_image_optimizer_cloud_key',
					91  => 'ewww_image_optimizer_debug',
					92  => 'ewww_image_optimizer_defer',
					93  => 'ewww_image_optimizer_delay',
					94  => 'ewww_image_optimizer_delete_originals',
					95  => 'ewww_image_optimizer_disable_convert_links',
					96  => 'ewww_image_optimizer_disable_editor',
					97  => 'ewww_image_optimizer_disable_pngout',
					98  => 'ewww_image_optimizer_disable_resizes',
					99  => 'ewww_image_optimizer_disable_resizes_opt',
					100 => 'ewww_image_optimizer_dismiss_media_notice',
					101 => 'ewww_image_optimizer_enable_cloudinary',
					102 => 'ewww_image_optimizer_enable_help_notice',
					103 => 'ewww_image_optimizer_exactdn',
					104 => 'ewww_image_optimizer_exclude_paths',
					105 => 'ewww_image_optimizer_flag_attachments',
					106 => 'ewww_image_optimizer_gif_level',
					107 => 'ewww_image_optimizer_gif_to_png',
					108 => 'ewww_image_optimizer_include_media_paths',
					109 => 'ewww_image_optimizer_jpegtran_copy',
					110 => 'ewww_image_optimizer_jpg_background',
					111 => 'ewww_image_optimizer_jpg_level',
					112 => 'ewww_image_optimizer_jpg_quality',
					113 => 'ewww_image_optimizer_jpg_to_png',
					114 => 'ewww_image_optimizer_lazy_load',
					115 => 'ewww_image_optimizer_lossy_skip_full',
					116 => 'ewww_image_optimizer_maxmediaheight',
					117 => 'ewww_image_optimizer_maxmediawidth',
					118 => 'ewww_image_optimizer_maxotherheight',
					119 => 'ewww_image_optimizer_maxotherwidth',
					120 => 'ewww_image_optimizer_metadata_remove',
					121 => 'ewww_image_optimizer_metadata_skip_full',
					122 => 'ewww_image_optimizer_ngg_attachments',
					123 => 'ewww_image_optimizer_noauto',
					124 => 'ewww_image_optimizer_optipng_level',
					125 => 'ewww_image_optimizer_pdf_level',
					126 => 'ewww_image_optimizer_png_level',
					127 => 'ewww_image_optimizer_png_to_jpg',
					128 => 'ewww_image_optimizer_pngout_level',
					129 => 'ewww_image_optimizer_relative_migration_status',
					130 => 'ewww_image_optimizer_scanning_attachments',
					131 => 'ewww_image_optimizer_skip_bundle',
					132 => 'ewww_image_optimizer_skip_png_size',
					133 => 'ewww_image_optimizer_skip_size',
					134 => 'ewww_image_optimizer_tracking_notice',
					135 => 'ewww_image_optimizer_version',
					136 => 'ewww_image_optimizer_webp',
					137 => 'ewww_image_optimizer_webp_for_cdn',
					138 => 'ewww_image_optimizer_webp_paths',
					139 => 'exactdn_all_the_things',
					140 => 'exactdn_lossy',
					141 => 'finished_splitting_shared_terms',
					142 => 'fresh_site',
					143 => 'fusion_applied_patches',
					144 => 'fusion_builder_settings',
					145 => 'fusion_builder_version',
					146 => 'fusion_core_flush_permalinks',
					147 => 'fusion_core_unconverted_posts_converted',
					148 => 'fusion_core_version',
					149 => 'fusion_dynamic_css_ids',
					150 => 'fusion_dynamic_css_posts',
					151 => 'fusion_dynamic_css_time',
					152 => 'fusion_map_addresses',
					153 => 'fusion_options',
					154 => 'fusion_options-transients',
					155 => 'fusion_supported_plugins_active',
					156 => 'gf_db_version',
					157 => 'gf_dismissed_upgrades',
					158 => 'gf_is_upgrading',
					159 => 'gf_previous_db_version',
					160 => 'gf_site_key',
					161 => 'gf_site_secret',
					162 => 'gf_upgrade_lock',
					163 => 'gform_email_count',
					164 => 'gform_enable_background_updates',
					165 => 'gform_enable_noconflict',
					166 => 'gform_sticky_admin_messages',
					167 => 'gform_version_info',
					168 => 'gmt_offset',
					169 => 'gravityformsaddon_gravityformswebapi_version',
					170 => 'hack_file',
					171 => 'home',
					172 => 'html_type',
					173 => 'image_default_align',
					174 => 'image_default_link_type',
					175 => 'image_default_size',
					176 => 'initial_db_version',
					177 => 'large_size_h',
					178 => 'large_size_w',
					179 => 'wp_user_roles',
					180 => 'lc_user_roles',
					181 => 'link_manager_enabled',
					182 => 'links_updated_date_format',
					183 => 'mailserver_login',
					184 => 'mailserver_pass',
					185 => 'mailserver_port',
					186 => 'mailserver_url',
					187 => 'maintenance_db_version',
					188 => 'maintenance_options',
					189 => 'medium_large_size_h',
					190 => 'medium_large_size_w',
					191 => 'medium_size_h',
					192 => 'medium_size_w',
					193 => 'moderation_keys',
					194 => 'moderation_notify',
					195 => 'monsterinsights_current_version',
					196 => 'monsterinsights_db_version',
					197 => 'monsterinsights_over_time',
					198 => 'monsterinsights_review',
					199 => 'monsterinsights_settings',
					200 => 'monsterinsights_tracking_notice',
					201 => 'monsterinsights_usage_tracking_config',
					202 => 'monsterinsights_usage_tracking_last_checkin',
					203 => 'monsterinsights_version_upgraded_from',
					204 => 'monsterinsights_welcome_91',
					205 => 'nav_menu_options',
					206 => 'page_comments',
					207 => 'page_for_posts',
					208 => 'page_on_front',
					209 => 'permalink_structure',
					210 => 'ping_sites',
					211 => 'posts_per_page',
					212 => 'posts_per_rss',
					213 => 'r_notice_data',
					214 => 'recently_activated',
					215 => 'recently_edited',
					216 => 'recovery_keys',
					217 => 'recovery_mode_email_last_sent',
					218 => 'redirection_options',
					219 => 'redux_blast',
					220 => 'require_name_email',
					221 => 'rewrite_rules',
					222 => 'rg_form_version',
					223 => 'rg_gforms_captcha_private_key',
					224 => 'rg_gforms_captcha_public_key',
					225 => 'rg_gforms_currency',
					226 => 'rg_gforms_disable_css',
					227 => 'rg_gforms_enable_akismet',
					228 => 'rg_gforms_enable_html5',
					229 => 'rg_gforms_key',
					230 => 'rg_gforms_message',
					231 => 'rocket_analytics_notice_displayed',
					232 => 'rss_use_excerpt',
					233 => 'sbg_sidebars',
					234 => 'shop_catalog_image_size',
					235 => 'shop_single_image_size',
					236 => 'shop_thumbnail_image_size',
					237 => 'show_avatars',
					238 => 'show_comments_cookies_opt_in',
					239 => 'show_on_front',
					240 => 'sidebars_widgets',
					241 => 'site_icon',
					242 => 'siteurl',
					243 => 'start_of_week',
					244 => 'sticky_posts',
					245 => 'stylesheet',
					246 => 'tag_base',
					247 => 'template',
					248 => 'theme_mods_a',
					249 => 'theme_switched',
					250 => 'thread_comments',
					251 => 'thread_comments_depth',
					252 => 'thumbnail_crop',
					253 => 'thumbnail_size_h',
					254 => 'thumbnail_size_w',
					255 => 'time_format',
					256 => 'timezone_string',
					257 => 'uninstall_plugins',
					258 => 'upload_path',
					259 => 'upload_url_path',
					260 => 'uploads_use_yearmonth_folders',
					261 => 'use_balanceTags',
					262 => 'use_smilies',
					263 => 'use_trackback',
					264 => 'users_can_register',
					265 => 'wc_admin_install_timestamp',
					266 => 'wc_admin_last_orders_milestone',
					267 => 'wc_admin_version',
					268 => 'WCSSC_db_version',
					269 => 'WCSSC_options',
					270 => 'wf_plugin_act_error',
					271 => 'whl_page',
					272 => 'widget_ad_125_125-widget',
					273 => 'widget_archives',
					274 => 'widget_avada-vertical-menu-widget',
					275 => 'widget_calendar',
					276 => 'widget_categories',
					277 => 'widget_contact_info-widget',
					278 => 'widget_custom_html',
					279 => 'widget_facebook-like-widget',
					280 => 'widget_flickr-widget',
					281 => 'widget_fusion_author-widget',
					282 => 'widget_gform_widget',
					283 => 'widget_googlemapswidget',
					284 => 'widget_logic',
					285 => 'widget_media_audio',
					286 => 'widget_media_gallery',
					287 => 'widget_media_image',
					288 => 'widget_media_video',
					289 => 'widget_menu-widget',
					290 => 'widget_meta',
					291 => 'widget_nav_menu',
					292 => 'widget_pages',
					293 => 'widget_pyre_tabs-widget',
					294 => 'widget_recent_works-widget',
					295 => 'widget_recent-comments',
					296 => 'widget_recent-posts',
					297 => 'widget_rev-slider-widget',
					298 => 'widget_rss',
					299 => 'widget_search',
					300 => 'widget_simpleimage',
					301 => 'widget_social_links-widget',
					302 => 'widget_tag_cloud',
					303 => 'widget_text',
					304 => 'widget_tweets-widget',
					305 => 'widget_warp_breadcrumbs',
					306 => 'widget_woocommerce_layered_nav',
					307 => 'widget_woocommerce_layered_nav_filters',
					308 => 'widget_woocommerce_price_filter',
					309 => 'widget_woocommerce_product_categories',
					310 => 'widget_woocommerce_product_search',
					311 => 'widget_woocommerce_product_tag_cloud',
					312 => 'widget_woocommerce_products',
					313 => 'widget_woocommerce_rating_filter',
					314 => 'widget_woocommerce_recent_reviews',
					315 => 'widget_woocommerce_recently_viewed_products',
					316 => 'widget_woocommerce_top_rated_products',
					317 => 'widget_woocommerce_widget_cart',
					318 => 'woocommerce_admin_notices',
					319 => 'woocommerce_all_except_countries',
					320 => 'woocommerce_allow_bulk_remove_personal_data',
					321 => 'woocommerce_allow_tracking',
					322 => 'woocommerce_allowed_countries',
					323 => 'woocommerce_anonymize_completed_orders',
					324 => 'woocommerce_api_enabled',
					325 => 'woocommerce_calc_discounts_sequentially',
					326 => 'woocommerce_calc_taxes',
					327 => 'woocommerce_cart_page_id',
					328 => 'woocommerce_cart_redirect_after_add',
					329 => 'woocommerce_checkout_highlight_required_fields',
					330 => 'woocommerce_checkout_order_received_endpoint',
					331 => 'woocommerce_checkout_page_id',
					332 => 'woocommerce_checkout_pay_endpoint',
					333 => 'woocommerce_checkout_privacy_policy_text',
					334 => 'woocommerce_currency',
					335 => 'woocommerce_currency_pos',
					336 => 'woocommerce_db_version',
					337 => 'woocommerce_default_country',
					338 => 'woocommerce_default_customer_address',
					339 => 'woocommerce_delete_inactive_accounts',
					340 => 'woocommerce_demo_store',
					341 => 'woocommerce_dimension_unit',
					342 => 'woocommerce_downloads_grant_access_after_payment',
					343 => 'woocommerce_downloads_require_login',
					344 => 'woocommerce_email_background_color',
					345 => 'woocommerce_email_base_color',
					346 => 'woocommerce_email_body_background_color',
					347 => 'woocommerce_email_footer_text',
					348 => 'woocommerce_email_from_address',
					349 => 'woocommerce_email_from_name',
					350 => 'woocommerce_email_header_image',
					351 => 'woocommerce_email_text_color',
					352 => 'woocommerce_enable_ajax_add_to_cart',
					353 => 'woocommerce_enable_checkout_login_reminder',
					354 => 'woocommerce_enable_coupons',
					355 => 'woocommerce_enable_guest_checkout',
					356 => 'woocommerce_enable_myaccount_registration',
					357 => 'woocommerce_enable_review_rating',
					358 => 'woocommerce_enable_reviews',
					359 => 'woocommerce_enable_shipping_calc',
					360 => 'woocommerce_enable_signup_and_login_from_checkout',
					361 => 'woocommerce_erasure_request_removes_download_data',
					362 => 'woocommerce_erasure_request_removes_order_data',
					363 => 'woocommerce_file_download_method',
					364 => 'woocommerce_hide_out_of_stock_items',
					365 => 'woocommerce_hold_stock_minutes',
					366 => 'woocommerce_logout_endpoint',
					367 => 'woocommerce_manage_stock',
					368 => 'woocommerce_meta_box_errors',
					369 => 'woocommerce_myaccount_add_payment_method_endpoint',
					370 => 'woocommerce_myaccount_delete_payment_method_endpoint',
					371 => 'woocommerce_myaccount_downloads_endpoint',
					372 => 'woocommerce_myaccount_edit_account_endpoint',
					373 => 'woocommerce_myaccount_edit_address_endpoint',
					374 => 'woocommerce_myaccount_lost_password_endpoint',
					375 => 'woocommerce_myaccount_orders_endpoint',
					376 => 'woocommerce_myaccount_page_id',
					377 => 'woocommerce_myaccount_payment_methods_endpoint',
					378 => 'woocommerce_myaccount_set_default_payment_method_endpoint',
					379 => 'woocommerce_myaccount_view_order_endpoint',
					380 => 'woocommerce_notify_low_stock',
					381 => 'woocommerce_notify_low_stock_amount',
					382 => 'woocommerce_notify_no_stock',
					383 => 'woocommerce_notify_no_stock_amount',
					384 => 'woocommerce_permalinks',
					385 => 'woocommerce_placeholder_image',
					386 => 'woocommerce_price_decimal_sep',
					387 => 'woocommerce_price_display_suffix',
					388 => 'woocommerce_price_num_decimals',
					389 => 'woocommerce_price_thousand_sep',
					390 => 'woocommerce_prices_include_tax',
					391 => 'woocommerce_queue_flush_rewrite_rules',
					392 => 'woocommerce_registration_generate_password',
					393 => 'woocommerce_registration_generate_username',
					394 => 'woocommerce_registration_privacy_policy_text',
					395 => 'woocommerce_review_rating_required',
					396 => 'woocommerce_review_rating_verification_label',
					397 => 'woocommerce_review_rating_verification_required',
					398 => 'woocommerce_ship_to_countries',
					399 => 'woocommerce_ship_to_destination',
					400 => 'woocommerce_shipping_cost_requires_address',
					401 => 'woocommerce_shipping_debug_mode',
					402 => 'woocommerce_shipping_tax_class',
					403 => 'woocommerce_shop_page_id',
					404 => 'woocommerce_show_marketplace_suggestions',
					405 => 'woocommerce_single_image_width',
					406 => 'woocommerce_specific_allowed_countries',
					407 => 'woocommerce_specific_ship_to_countries',
					408 => 'woocommerce_stock_email_recipient',
					409 => 'woocommerce_stock_format',
					410 => 'woocommerce_store_address',
					411 => 'woocommerce_store_address_2',
					412 => 'woocommerce_store_city',
					413 => 'woocommerce_store_postcode',
					414 => 'woocommerce_tax_based_on',
					415 => 'woocommerce_tax_classes',
					416 => 'woocommerce_tax_display_cart',
					417 => 'woocommerce_tax_display_shop',
					418 => 'woocommerce_tax_round_at_subtotal',
					419 => 'woocommerce_tax_total_display',
					420 => 'woocommerce_terms_page_id',
					421 => 'woocommerce_thumbnail_image_width',
					422 => 'woocommerce_trash_cancelled_orders',
					423 => 'woocommerce_trash_failed_orders',
					424 => 'woocommerce_trash_pending_orders',
					425 => 'woocommerce_version',
					426 => 'woocommerce_weight_unit',
					427 => 'wordfence_installed',
					428 => 'wordfence_lastSyncAttackData',
					429 => 'wordfence_ls_version',
					430 => 'wordfence_syncAttackDataAttempts',
					431 => 'wordfence_syncingAttackData',
					432 => 'wordfence_version',
					433 => 'wordfenceActivated',
					434 => 'wp_page_for_privacy_policy',
					435 => 'wp_rocket_settings',
					436 => 'wp_stream',
					437 => 'wp_stream_db',
					438 => 'WPLANG',
					439 => 'wpsdb_settings',
					440 => 'wpseo',
					441 => 'wpseo_dismiss_recalculate',
					442 => 'wpseo_flush_rewrite',
					443 => 'wpseo_license_server_version',
					444 => 'wpseo_social',
					445 => 'wpseo_titles',
					446 => 'ws_menu_editor',
					447 => 'zerospam_db_version',
					448 => 'zerospam_general_settings',
					449 => 'zerospam_key',
				],
				'allow_null'         => 1,
				'multiple'           => 1,
				'ui'                 => 1,
				'ajax'               => 0,
				'return_format'      => 'value',
				'lct_preset_choices' => '',
				'lct_class_selector' => '',
				'placeholder'        => '',
				'menu_order'         => 2,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_dev',
				],
			],
		],
		'menu_order'                 => 24,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

endif;
