<?php
//Do not allow directly accessing this file
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


if ( ! lct_get_setting( 'acf_dev' ) ):

	acf_add_local_field_group( [
		'key'                        => 'group_56db14df1d7a9',
		'title'                      => 'Review::: Site Info',
		'fields'                     => [
			[
				'key'               => 'field_56db14df2e5de',
				'label'             => 'site_info',
				'name'              => 'lct_review_site_info:::lct_fix',
				'aria-label'        => '',
				'type'              => 'oembed',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'width'             => '',
				'height'            => '',
				'menu_order'        => 0,
			],
			[
				'key'                => 'field_56db14df2e7e8',
				'label'              => 'Run This Now',
				'name'               => 'lct_review_site_info:::run_this',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Run This Now',
				'ui_off_text'        => 'Don\'t Run',
				'lct_class_selector' => '',
				'menu_order'         => 1,
			],
			[
				'key'                => 'field_56db14df2ea0d',
				'label'              => 'Save Field Values',
				'name'               => 'lct_review_site_info:::show_params::save_field_values',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => [
					[
						[
							'field'    => 'field_56db14df2ebee',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Save',
				'ui_off_text'        => 'Don\'t Save',
				'lct_class_selector' => '',
				'menu_order'         => 2,
			],
			[
				'key'                => 'field_56db14df2ebee',
				'label'              => 'Show Params to Non Developers',
				'name'               => 'lct_review_site_info:::show_params',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => 'If you can see this field and you are NOT a developer. Do NOT change it.',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '100',
					'class' => 'clear',
					'id'    => '',
				],
				'message'            => '',
				'default_value'      => 0,
				'ui'                 => 1,
				'ui_on_text'         => 'Show',
				'ui_off_text'        => 'Hide',
				'lct_class_selector' => '',
				'menu_order'         => 3,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_fixes_cleanups',
				],
			],
		],
		'menu_order'                 => 9,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_55b0076c9b2bd',
		'title'                      => 'DB Fix::: Add taxonomy field data to old entries',
		'fields'                     => [
			[
				'key'               => 'field_55b009663b857',
				'label'             => 'lct_fix',
				'name'              => 'db_fix_atfd_7637:::lct_fix',
				'aria-label'        => '',
				'type'              => 'oembed',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'width'             => '',
				'height'            => '',
				'menu_order'        => 0,
			],
			[
				'key'                => 'field_55b064d3f17c8',
				'label'              => 'Run This Now',
				'name'               => 'db_fix_atfd_7637:::run_this',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Run This Now',
				'ui_off_text'        => 'Don\'t Run',
				'lct_class_selector' => '',
				'menu_order'         => 1,
			],
			[
				'key'                => 'field_55b00dbfe155a',
				'label'              => 'Taxonomy',
				'name'               => 'db_fix_atfd_7637:::taxonomy',
				'aria-label'         => '',
				'type'               => 'text',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => '',
				'maxlength'          => '',
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'lct_class_selector' => '',
				'menu_order'         => 2,
			],
			[
				'key'                       => 'field_55b0783accbd9',
				'label'                     => 'Overwrite Existing Values',
				'name'                      => 'db_fix_atfd_7637:::overwrite_value',
				'aria-label'                => '',
				'type'                      => 'checkbox',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '50',
					'class' => 'hide_label',
					'id'    => '',
				],
				'layout'                    => 'vertical',
				'choices'                   => [
					1 => 'Overwrite Existing Values',
				],
				'default_value'             => [
				],
				'allow_custom'              => 0,
				'save_custom'               => 0,
				'toggle'                    => 0,
				'return_format'             => 'value',
				'lct_class_selector'        => '',
				'custom_choice_button_text' => 'Add new choice',
				'menu_order'                => 3,
			],
			[
				'key'                => 'field_55b0646530db8',
				'label'              => 'Field Key',
				'name'               => 'db_fix_atfd_7637:::f_key',
				'aria-label'         => '',
				'type'               => 'text',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => '',
				'maxlength'          => '',
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'lct_class_selector' => '',
				'menu_order'         => 4,
			],
			[
				'key'                => 'field_55b0649330db9',
				'label'              => 'Field Name',
				'name'               => 'db_fix_atfd_7637:::f_name',
				'aria-label'         => '',
				'type'               => 'text',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => 'alignright',
					'id'    => '',
				],
				'default_value'      => '',
				'maxlength'          => '',
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'lct_class_selector' => '',
				'menu_order'         => 5,
			],
			[
				'key'                => 'field_55b0717b4d5c3',
				'label'              => 'Option Value',
				'name'               => 'db_fix_atfd_7637:::option_value',
				'aria-label'         => '',
				'type'               => 'text',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => '',
				'maxlength'          => '',
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'lct_class_selector' => '',
				'menu_order'         => 6,
			],
			[
				'key'                       => 'field_55b2725121152',
				'label'                     => 'Is Array',
				'name'                      => 'db_fix_atfd_7637:::is_array',
				'aria-label'                => '',
				'type'                      => 'checkbox',
				'instructions'              => 'Separate each array value in Option Value with commas. Array KEY is not currently supported.',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '50',
					'class' => 'hide_label_show_desc alignright',
					'id'    => '',
				],
				'layout'                    => 'vertical',
				'choices'                   => [
					1 => 'Is Array',
				],
				'default_value'             => [
				],
				'allow_custom'              => 0,
				'save_custom'               => 0,
				'toggle'                    => 0,
				'return_format'             => 'value',
				'lct_class_selector'        => '',
				'custom_choice_button_text' => 'Add new choice',
				'menu_order'                => 7,
			],
			[
				'key'                => 'field_55b268246d39f',
				'label'              => 'Save Field Values',
				'name'               => 'db_fix_atfd_7637:::show_params::save_field_values',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => [
					[
						[
							'field'    => 'field_55b268ba7ae4c',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Save',
				'ui_off_text'        => 'Don\'t Save',
				'lct_class_selector' => '',
				'menu_order'         => 8,
			],
			[
				'key'                => 'field_55b268ba7ae4c',
				'label'              => 'Show Params to Non Developers',
				'name'               => 'db_fix_atfd_7637:::show_params',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => 'If you can see this field and you are NOT a developer. Do NOT change it.',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '100',
					'class' => 'clear',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Show',
				'ui_off_text'        => 'Hide',
				'lct_class_selector' => '',
				'menu_order'         => 9,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_fixes_cleanups',
				],
			],
		],
		'menu_order'                 => 10,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_55b95d013ee9d',
		'title'                      => 'DB Fix::: Add Post Meta to Multiple Posts',
		'fields'                     => [
			[
				'key'               => 'field_55b95d01505d0',
				'label'             => 'lct_fix',
				'name'              => 'db_fix_apmmp_5545:::lct_fix',
				'aria-label'        => '',
				'type'              => 'oembed',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'width'             => '',
				'height'            => '',
				'menu_order'        => 0,
			],
			[
				'key'                => 'field_55b95d01509af',
				'label'              => 'Run This Now',
				'name'               => 'db_fix_apmmp_5545:::run_this',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Run This Now',
				'ui_off_text'        => 'Don\'t Run',
				'lct_class_selector' => '',
				'menu_order'         => 1,
			],
			[
				'key'                => 'field_55b95d0150d96',
				'label'              => 'Post IDs to Add Meta Data To',
				'name'               => 'db_fix_apmmp_5545:::posts',
				'aria-label'         => '',
				'type'               => 'text',
				'instructions'       => 'Separate each post id in with commas.',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => '',
				'maxlength'          => '',
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'lct_class_selector' => '',
				'menu_order'         => 2,
			],
			[
				'key'                       => 'field_55b95d015117f',
				'label'                     => 'Force Overwrite Existing Values',
				'name'                      => 'db_fix_apmmp_5545:::overwrite_value',
				'aria-label'                => '',
				'type'                      => 'checkbox',
				'instructions'              => '',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '50',
					'class' => 'hide_label',
					'id'    => '',
				],
				'layout'                    => 'vertical',
				'choices'                   => [
					1 => 'Force Overwrite Existing Values',
				],
				'default_value'             => [
				],
				'allow_custom'              => 0,
				'save_custom'               => 0,
				'toggle'                    => 0,
				'return_format'             => 'value',
				'lct_class_selector'        => '',
				'custom_choice_button_text' => 'Add new choice',
				'menu_order'                => 3,
			],
			[
				'key'                => 'field_55b95d0151576',
				'label'              => 'Meta Key',
				'name'               => 'db_fix_apmmp_5545:::meta_key',
				'aria-label'         => '',
				'type'               => 'text',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => '',
				'maxlength'          => '',
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'lct_class_selector' => '',
				'menu_order'         => 4,
			],
			[
				'key'                => 'field_55b95d0151d37',
				'label'              => 'Meta Value',
				'name'               => 'db_fix_apmmp_5545:::meta_value',
				'aria-label'         => '',
				'type'               => 'text',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '50',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => '',
				'maxlength'          => '',
				'placeholder'        => '',
				'prepend'            => '',
				'append'             => '',
				'lct_class_selector' => '',
				'menu_order'         => 5,
			],
			[
				'key'                       => 'field_55b95d0152126',
				'label'                     => 'Is Array',
				'name'                      => 'db_fix_apmmp_5545:::is_array',
				'aria-label'                => '',
				'type'                      => 'checkbox',
				'instructions'              => 'Separate each array value in Meta Value with commas. Array KEY is not currently supported.',
				'required'                  => 0,
				'conditional_logic'         => 0,
				'wrapper'                   => [
					'width' => '50',
					'class' => 'hide_label_show_desc alignright',
					'id'    => '',
				],
				'layout'                    => 'vertical',
				'choices'                   => [
					1 => 'Is Array',
				],
				'default_value'             => [
				],
				'allow_custom'              => 0,
				'save_custom'               => 0,
				'toggle'                    => 0,
				'return_format'             => 'value',
				'lct_class_selector'        => '',
				'custom_choice_button_text' => 'Add new choice',
				'menu_order'                => 6,
			],
			[
				'key'                => 'field_55b95d0152508',
				'label'              => 'Save Field Values',
				'name'               => 'db_fix_apmmp_5545:::show_params::save_field_values',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => [
					[
						[
							'field'    => 'field_55b95d01528ed',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Save',
				'ui_off_text'        => 'Don\'t Save',
				'lct_class_selector' => '',
				'menu_order'         => 7,
			],
			[
				'key'                => 'field_55b95d01528ed',
				'label'              => 'Show Params to Non Developers',
				'name'               => 'db_fix_apmmp_5545:::show_params',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => 'If you can see this field and you are NOT a developer. Do NOT change it.',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '100',
					'class' => 'clear',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Show',
				'ui_off_text'        => 'Hide',
				'lct_class_selector' => '',
				'menu_order'         => 8,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_fixes_cleanups',
				],
			],
		],
		'menu_order'                 => 11,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );

	acf_add_local_field_group( [
		'key'                        => 'group_55fdae0f56605',
		'title'                      => 'File Fix::: Run _editzz File Overwrite',
		'fields'                     => [
			[
				'key'               => 'field_55fdae0f6723e',
				'label'             => 'lct_fix',
				'name'              => 'file_fix_editzz_or:::lct_fix',
				'aria-label'        => '',
				'type'              => 'oembed',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'width'             => '',
				'height'            => '',
				'menu_order'        => 0,
			],
			[
				'key'                => 'field_55fdae0f675f4',
				'label'              => 'Run This Now',
				'name'               => 'file_fix_editzz_or:::run_this',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Run This Now',
				'ui_off_text'        => 'Don\'t Run',
				'lct_class_selector' => '',
				'menu_order'         => 1,
			],
			[
				'key'                => 'field_55fdae0f691a5',
				'label'              => 'Save Field Values',
				'name'               => 'file_fix_editzz_or:::show_params::save_field_values',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => '',
				'required'           => 0,
				'conditional_logic'  => [
					[
						[
							'field'    => 'field_55fdae0f6958d',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'            => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Save',
				'ui_off_text'        => 'Don\'t Save',
				'lct_class_selector' => '',
				'menu_order'         => 2,
			],
			[
				'key'                => 'field_55fdae0f6958d',
				'label'              => 'Show Params to Non Developers',
				'name'               => 'file_fix_editzz_or:::show_params',
				'aria-label'         => '',
				'type'               => 'true_false',
				'instructions'       => 'If you can see this field and you are NOT a developer. Do NOT change it.',
				'required'           => 0,
				'conditional_logic'  => 0,
				'wrapper'            => [
					'width' => '100',
					'class' => 'clear',
					'id'    => '',
				],
				'default_value'      => 0,
				'message'            => '',
				'ui'                 => 1,
				'ui_on_text'         => 'Show',
				'ui_off_text'        => 'Hide',
				'lct_class_selector' => '',
				'menu_order'         => 3,
			],
		],
		'location'                   => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_fixes_cleanups',
				],
			],
		],
		'menu_order'                 => 12,
		'position'                   => 'normal',
		'style'                      => 'default',
		'label_placement'            => 'top',
		'instruction_placement'      => 'label',
		'hide_on_screen'             => '',
		'active'                     => true,
		'description'                => '',
		'show_in_rest'               => 1,
		'afwp_use_exclude_audit_acf' => 0,
	] );
	
endif;
